global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          group: 'prometheus'
      - targets: ['cadvisor:8080']
        labels:
          group: 'docker'
