services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

  mysqld-exporter:
    image: prom/mysqld-exporter:v0.12.1
    container_name: mysqld-exporter
    environment:
      DATA_SOURCE_NAME: "root:rootpassword@(mysql:3306)/"
    ports:
      - "9104:9104"
    volumes:
      - ./my.cnf:/root/.my.cnf
    networks:
      - monitoring

  sysbench:
    image: severalnines/sysbench
    container_name: sysbench
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - monitoring

volumes:
  mysql-data:
  grafana-storage:

networks:
  monitoring:

