services:
  mysql_master:
    image: mysql:8.0
    container_name: mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_REPLICATION_USER: repluser
      MYSQL_REPLICATION_PASSWORD: replpassword
      MYSQL_DATABASE: testdb
    volumes:
      - master_data:/var/lib/mysql
      - ./master-init.sql:/docker-entrypoint-initdb.d/master-init.sql
      - ./mysql_master/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"

  mysql_slave:
    image: mysql:8.0
    container_name: mysql_slave
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_REPLICATION_USER: repluser
      MYSQL_REPLICATION_PASSWORD: replpassword
    volumes:
      - slave_data:/var/lib/mysql
      - ./mysql_slave/conf/my.cnf:/etc/mysql/my.cnf
    depends_on:
      - mysql_master
    ports:
      - "3307:3306"

volumes:
  master_data:
  slave_data:

